class Constants {
	static readonly LOCAL_STORAGE_ACCESS_TOKEN_KEY = "LOCAL_STORAGE_ACCESS_TOKEN_KEY"
	static readonly LOCAL_STORAGE_REFRESH_TOKEN_KEY = "LOCAL_STORAGE_REFRESH_TOKEN_KEY"
	static readonly LOCAL_STORAGE_USER_INFO = "LOCAL_STORAGE_USER_INFO"
	static readonly LOCAL_USER_REGISTER_INFO = "LOCAL_USER_REGISTER_INFO"
	static readonly LOCAL_USER_FIRST_LOGIN = "LOCAL_USER_FIRST_LOGIN"
	static readonly LOCAL_USER_FIRST_TUTORIAL = "LOCAL_USER_FIRST_TUTORIAL"
	static readonly LOCAL_USER_REGISTER_LOGIN = "LOCAL_USER_REGISTER_LOGIN"
	static readonly LOCAL_USER_FIRST_NOTICE = "LOCAL_USER_FIRST_NOTICE"
	static readonly APP_PERMISSION_NOTICE = "APP_PERMISSION_NOTICE"
}

export default Constants
